# Page settings

baseurl = "//chris.hiszpanski.name/"
languageCode = "en-us"
title = "Chris Hiszpanski"
theme = "orbit"
googleAnalytics = "UA-92228276-1"

# Do not build files for websites. Need them? Set to false
disableKinds = [ "RSS", "Sitemap" ]

[params]

# Meta
    description = "Ahoy!"
    author = "Chris Hiszpanski"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css?20200122"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Chris Hiszpanski"
#        tagline = "Software · Embedded · Computer Vision · Linux · Machine Learning"
        avatar = "https://avatars1.githubusercontent.com/u/1595195?s=100&v=4"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "location"
        icon = "fa-map-marker"
        title = "Los Angeles, California"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: chris@hiszpanski.name"
        title = "chris@hiszpanski.name"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/thinkski"
        title = "github.com/thinkski"

        [[params.contact.list]]
        class = "gpg"
        icon = "fa-key"
        url = "publickey.chris@hiszpanski.name.txt"
        title = "public key"
        download = true

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Electrical Engineering"
        college = "Caltech"
        dates = "2006 - 2007"

        [[params.education.list]]
        degree = "BSc in Electrical Engineering"
        college = "Caltech"
        dates = "2002 - 2006"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Polish"
        level = "Fluent"

    # Interests section
    [params.interests]
        enable = true
        title = "Skillsets"

        [[params.interests.list]]
        interest = "Artificial intelligence"

        [[params.interests.list]]
        interest = "AWS"

        [[params.interests.list]]
        interest = "Computer vision"

        [[params.interests.list]]
        interest = "Cryptography · Security"

        [[params.interests.list]]
        interest = "Deep learning: Caffe · PyTorch · Tensorflow"

        [[params.interests.list]]
        interest = "Dev ops: Ansible · Chef · Docker · Kubernetes"

        [[params.interests.list]]
        interest = "Digital signal processing"

        [[params.interests.list]]
        interest = "Distributed systems"

        [[params.interests.list]]
        interest = "Embedded systems: Busybox · LTIB · Yocto"

        [[params.interests.list]]
        interest = "FPGAs: VHDL"

        [[params.interests.list]]
        interest = "Frontend: Preact · TailwindCSS"

        [[params.interests.list]]
        interest = "Go · C · Python"

        [[params.interests.list]]
        interest = "Hardware: Altium · OrCAD"

        [[params.interests.list]]
        interest = "Linux: Autotools · CMake · Git"

        [[params.interests.list]]
        interest = "Machine learning"

        [[params.interests.list]]
        interest = "OpenGL ES 3.1"

        [[params.interests.list]]
        interest = "Reinforcement learning"

        [[params.interests.list]]
        interest = "Reverse engineering"

        [[params.interests.list]]
        interest = "WebRTC: DTLS · ICE · RTP · SDP · STUN · TURN"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Chris Hiszpanski"
        summary = "I enjoy building systems, beautiful state-of-the-art systems which are fault tolerant, scalable, secure, and as simple as possible, systems which optimize across many variables, including cost and development time, to yield elegant solutions which make the world better. Most recently, I have been developing distributed and machine learning systems. At <a href=\"https://getkuna.com\">Kuna</a>, I created the computer vision platform for an internet-of-things camera network. Previously, I developed embedded systems. I created schematics, printed circuit board layouts, and firmware for a variety of devices, including three software-defined radios, a commercial drone autopilot, a voice-over-IP telephone, and a vehicle remote-control and tracking device."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Software Engineer, Streaming"
        dates = "2020 - Present"
        company = "Verkada"
        location = "San Mateo, California (Remote)"
        logo = "verkada.png"
        url = "https://verkada.com"

        [[params.jobs.list]]
        position = "Founder"
        dates = "2019 - 2020"
        company = "Lanikai Labs"
        location = "San Mateo, California"
        logo = "lanikai.png"
        url = "https://lanikailabs.com"
        details = '''Lanikai Labs provides [AlohaRTC](https://alohartc.com), a real-time video communication platform for smart cameras, robotics, telepresence, teleoperation and other connected devices.

* Simple. Easy drop-in integration.</li>
* Secure. End-to-end encrypted video, audio, and remote control.</li>
* Supported. Connect from any mobile or desktop browser – without plug-ins.
* Stellar. Crystal clear video, in town or across the globe, even in tough network conditions.

Engineering team acquired by Verkada.
'''

        [[params.jobs.list]]
        position = "Staff Machine Vision Engineer"
        dates = "2017 - 2019"
        company = "Tesla"
        location = "Palo Alto, California"
        logo = "tesla.png"
        url = "https://tesla.com"

        [[params.jobs.list]]
        position = "Chief Architect"
        dates = "2014 - 2017"
        company = "Kuna"
        location = "San Bruno, California"
	logo = "kuna.png"
        url = "https://getkuna.com"
        details = "First hire. Built-out much of the early camera firmware, backend cloud architecture, automated testing and CI/CD workflow. Gave birth to Sight and Kuna AI, a horizontally scalable, low-latency, cost-efficient, and high-accuracy computer vision pipeline for detecting objects of interest via deep convolutional neural networks on a GPU cluster. Focused on making homes and neighborhoods safer for customers via intelligent camera networks a reality, a neighborhood watch for the 21st century."

        [[params.jobs.list]]
        position = "Lead Embedded Software Engineer"
        dates = "2013 - 2014"
        company = "Airware"
        location = "San Francisco, California"
	logo = "airware.png"
        url = "https://airware.com"
        details = "Led firmware team, setting direction and managing sprints. Designed single-board computer for new UAV autopilot product (fixed-wing, quad-copter, VTOL). Developed board support packages for embedded Linux and Micrium uC/OS-II. Designed bootloader and other safety-critical firmware components."

        [[params.jobs.list]]
        position = "Software and Hardware Engineer"
        dates = "2006 - 2013"
        company = "U.S. Department of Defense"
        location = "Washington, D.C."
        logo = "dod.png"

        [[params.jobs.list]]
        position = "Intern"
        dates = "2002"
        company = "Jet Propulsion Laboratory"
        location = "Pasadena, California"
        url = "https://www.jpl.nasa.gov"
        logo = "nasa.png"
        details = "Designed a firmware bootloader for Rocky 7, a terrestrial testbed for the Mars Exploration Rover (MER). Bootloader instances embedded within rover peripherals accepted Microchip PIC firmware from a VxWorks on-board computer, enabling remote firmware upgrades. Received a full-time firmware engineer job offer based on results."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"

        [[params.projects.list]]
        title = "Alohacam"
        url = "https://alohacam.io"
        tagline = "Real-time low-latency video communication between a Raspberry Pi and any web browser using WebRTC. Written in Go, Preact. Embedded WebRTC stack written from scratch."
        year = "2019"


        [[params.projects.list]]
        title = "Cytosight"
        url = "/projects/cytosight"
        tagline = "Machine vision based cytometer. Convolutional neural network running on serverless backend."
        year = "2017"

        [[params.projects.list]]
        title = "Hashpipe"
        url = "//github.com/thinkski/hashpipe"
        tagline = "VHDL implementation of a systolic SHA-256 hashing engine for Bitcoin. 10x more hashes per joule than a GPU."
        year = "2011"

        [[params.projects.list]]
        title = "iTrack"
        url = "//www.scribd.com/document/92697088/Circuit-Cellar-199-Feb-2007"
        tagline = "Published in Circuit Cellar Issue #199. DSP-Based Vehicle Monitoring."
        year = "2006"

        [[params.projects.list]]
        title = "Solf"
        url = "//thinkski.github.io/solf"
        tagline = "Interactive solvent finder for chemical engineers. Single-page client-side app using jQuery and Datatables.js."
        year = "2012"

        [[params.projects.list]]
        title = "Sorad"
        url = "//sorad.io"
        tagline = "Software-defined radio. A swiss army knife for real-time signal processing."
        year = "2007 - Present"

        [[params.projects.list]]
        title = "ValentineGL"
        url = "//github.com/thinkski/ValentineGL"
        tagline = "Beating heart screensaver for Mac OS X. Marching cubes algorithm in OpenGL."
        year = "2012"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Chris Hiszpanski. All rights reserved."
