version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Run Hugo"
          command: hugo -v -d /tmp/workspace/public
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=300" \
            --delete \
            --size-only
          from: /tmp/workspace/public/
          to: s3://chris.hiszpanski.name/

workflows:
  version: 2
  commit:
    jobs:
      - build
